### ISSUE TITLE
Event Change 

### ISSUE THREAD

**Issue by jigudo** [catalyst/magento_moodle_connector#1]
Hi,

I am running Magento 1.8.1.0 and Moodle 2.5. I am using IWD Onepage Checkout with Custom Theme and Paypal as a payment method. When I first tried these modules as is, My checkout page will not direct the user to Paypal site to make payments so I changed the event to "checkout_onepage_controller_success_action" in config file.

With this small change, I got the system to redirect to paypal page where users can make payments and get redirected to success one page. but the onepage checkout success page stays blank (it will look like if the IE/Chrome is still trying to load the page). I see that the order has been created but the moodle webservice is not called.

Am I missing anything here? I was hoping to have the moodle webservice called and the transactions written there as well as user to be displayed with the order number which they would get without the module.

Thank you,
Jignashu

**Comment by jigudo** [comment]
Just for the note, I tried to build the module to enrol only while relying the standard moodle webservice for manual enrollment which enrols the user by user id "assuming that the system stays in synch for the user id), role id (default "5") and the course id ("SKU") with SOAP protocol. I used the event  "checkout_onepage_controller_success_action" and had a same issue.

**Comment by edwinp-catalyst-eu** [comment]
Hi, sounds like a general configuration issue. Will have some documentation for this shortly, in the mean time try using XMLRPC protocol in Moodle and creating a custom product attribute in Magento with the code moodle_id. With PayPal, I recommend using PayPal Pro option until the next update. Email me directly on the email address in the code header comments if you need any more pointers on configuration. Thanks.
